FROM registry.fedoraproject.org/fedora:37

# Add packages so that distrobox enter is fast
RUN dnf install -y bash bc curl diffutils dnf-plugins-core findutils gnupg2 less lsof ncurses passwd pinentry \
        procps-ng shadow-utils sudo time util-linux wget vte-profile terminator rclone && \
    dnf clean all

# Add rpmfusion repo
RUN dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
        https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
    dnf clean all

# Add brave repo
RUN dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/ && \
    rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc && \
    dnf clean all

# Install packages from non-fedora sources
RUN dnf install -y brave-browser vlc xeyes tree unzip nautilus ffmpeg && \
    dnf clean all

# Add special files
ADD files/pump-up-the-volume.sh /usr/local/bin

# Add custom ca certs
ADD files/tnet-self-signed-ca-cert.crt.pem /etc/pki/ca-trust/source/anchors/
RUN update-ca-trust

# Make sure the image is up to date (should be run close to last)
RUN dnf update -y && \
    dnf clean all

# Launch only if requirements are met (must be last or updates will stomp)
RUN mv /opt/brave.com/brave/brave /opt/brave.com/brave/brave-real
ADD files/run-if-requirements-met.sh /opt/brave.com/brave/brave
