
name: Build
on:
  schedule:
    - cron: "21 21 * * *"
  push:
    branches: ["main"]
  workflow_dispatch: # This line enables manual triggering

env:
  REGISTRY: ghcr.io
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  ubuntu-2404:
    env:
      SRC_DIR: ubuntu/24.04
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh

  fedora-44:
    env:
      SRC_DIR: fedora/44
    runs-on: ubuntu-latest
    steps:
      - name: Install xonsh
        run: |
          sudo apt update
          sudo apt install -y xonsh

      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Build container image
        run: |
          pushd "${{ env.SRC_DIR }}"
          ./build.xsh

      - name: Push container image
        run: |
          podman login "${{ env.IMAGE_REGISTRY }}" -u "${{ env.REGISTRY_USER }}" -p "${{ env.REGISTRY_PASSWORD }}"
          pushd "${{ env.SRC_DIR }}"
          ./push.xsh
